name: Запрос фичи
description: Предложить новую функциональность или улучшение
title: "[Feature]: "
labels:
  - type:feature
  - priority:low
body:
  - type: textarea
    id: problem
    attributes:
      label: Проблема
      description: Какую проблему решает эта фича?
      placeholder: "Меня раздражает когда..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
      description: Как должна работать эта фича?
      placeholder: "Должно работать так..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы
      description: Какие другие решения вы рассматривали?

  - type: checkboxes
    id: checklist
    attributes:
      label: Чек-лист
      options:
        - label: Я поискал похожие запросы фич
          required: true
        - label: Я готов помочь с реализацией
          required: false
