name: Задача
description: Техническая задача или улучшение
title: "[Task]: "
labels:
  - type:task
body:
  - type: textarea
    id: description
    attributes:
      label: Описание задачи
      description: Что нужно сделать?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Область
      description: Какая часть кодовой базы затрагивается?
      multiple: true
      options:
        - Backend
        - Frontend
        - Database
        - Infrastructure
    validations:
      required: true

  - type: checkboxes
    id: subtasks
    attributes:
      label: Подзадачи
      description: Разбейте задачу на части, если возможно
      options:
        - label: Подзадача 1
        - label: Подзадача 2
